---
title: "tidy_data"
output: github_document
---
```{r}
library(tidyverse)
library(leaflet)
library(dplyr)
library(ggplot2)
library(ggridges)
library(patchwork)
library(rnoaa)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```



## load the airbnb data
```{r}
devtools::install_github("p8105/p8105.datasets")
library(p8105.datasets)
data("nyc_airbnb")
```


## brainstorm some questions

* what is the best airbnb in staten island for less than $100
* what price range is most popular in each borough? most rented?
* what apartment features are related to price?
* cheapest room type in each neighborhood
* hosts have higher ratings?
```{r}
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2)
  
```

```{r}
nyc_airbnb %>% 
  count(neighbourhood_group, room_type) %>% 
  pivot_wider(names_from = room_type, values_from = n)
```

```{r}
nyc_airbnb %>% 
  group_by(neighbourhood_group, room_type) %>% 
  summarize(mean_price = mean(price))
```

```{r}
nyc_airbnb %>% 
  filter(price > 1000) %>% 
  ggplot(aes(x = neighbourhood_group, y = price)) +
  geom_boxplot()
```

```{r}
nyc_airbnb %>% 
  filter(neighbourhood_group == "Manhattan") %>% 
  count(neighbourhood)
  
```
```{r}
nyc_airbnb %>% 
  sample_n(1000) %>% 
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point()
```

## Create aleaflet map


```{r}
pal <- colorNumeric("magma", nyc_airbnb %>% pull(stars))

nyc_airbnb %>% 
  sample_n(500) %>% 
  leaflet() %>% 
  addTiles() %>% 
  addCircleMarkers(~lat, ~long, radius = 3, color =~ pal(price))
```

